declare const styles: {
  readonly "data-grid": string;
  readonly "data-grid-body": string;
  readonly "data-grid-cell": string;
  readonly "data-grid-color-cell": string;
  readonly "data-grid-color-swatch": string;
  readonly "data-grid-color-text": string;
  readonly "data-grid-editor": string;
  readonly "data-grid-footer": string;
  readonly "data-grid-footer-cell": string;
  readonly "data-grid-footer-row": string;
  readonly "data-grid-header": string;
  readonly "data-grid-header-cell": string;
  readonly "data-grid-header-row": string;
  readonly "data-grid-resizer": string;
  readonly "data-grid-row": string;
  readonly "data-grid-scrollable-columns": string;
  readonly "data-grid-sort-indicator": string;
  readonly "data-grid-sort-number": string;
  readonly "data-grid-virtual-spacer": string;
  readonly "disabled": string;
  readonly "editable": string;
  readonly "hide-scrollbar": string;
  readonly "pinned-left": string;
  readonly "pinned-right": string;
  readonly "resizing": string;
  readonly "selected": string;
  readonly "sortable": string;
};
export = styles;

